return {
  "Konfekt/FastFold",
  "NoahTheDuke/vim-just",
  "andymass/vim-matchup",
  "cappyzawa/starlark.vim",
  "dag/vim-fish",
  "github/copilot.vim",
  "glench/vim-jinja2-syntax",
  "google/vim-jsonnet",
  "grafana/vim-alloy",
  "jremmen/vim-ripgrep",
  -- "kien/ctrlp.vim",
  "neovim/nvim-lspconfig",
  "nickeb96/fish.vim",
  "nvim-lua/plenary.nvim",
  "preservim/nerdtree",
  "ray-x/go.nvim",
  "sharkdp/fd",
  "terryma/vim-expand-region",
  -- "tmhedberg/SimpylFold",
  "towolf/vim-helm",
  "tpope/vim-commentary",
  "tpope/vim-fugitive",
  "tpope/vim-obsession",
  "tpope/vim-rhubarb",
  "tpope/vim-surround",
}
