font=Hack Nerd Font Mono:size=12
selection-target=both
[colors-dark]
alpha=0.9
background=000000
foreground=00ff00
# regular0..regular7=
# bright0..bright7=
# foreground=afff00
# foreground=afff87
# word-delimiters=
# # how do we do this now
