vim.opt_local.tabstop = 2
vim.opt_local.softtabstop = 2
vim.opt_local.shiftwidth = 2
vim.opt_local.textwidth = 0
vim.opt_local.expandtab = true
vim.opt_local.autoindent = true
vim.opt_local.fileformat = 'unix'
vim.b.ale_fixers = {'prettier', 'remove_trailing_lines', 'trim_whitespace'}
vim.b.ale_fix_on_save = 0
